# Generated by Django 3.1.7 on 2021-03-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_type', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255, null=True)),
                ('passport_series', models.IntegerField(max_length=4)),
                ('passport_number', models.IntegerField(max_length=6)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_entrepreneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('inn', models.PositiveIntegerField(max_length=12)),
                ('ogrnip', models.IntegerField(max_length=15)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='Entits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('inn', models.IntegerField(max_length=10)),
                ('ogrn', models.IntegerField(max_length=13)),
                ('address', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tenants')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_lease', models.DateField(auto_now_add=True)),
                ('end_of_lease', models.DateField(auto_now_add=True)),
                ('date_of_signing_the_deal', models.DateField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField()),
                ('additional_services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_side.additional_services')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_side.discount_cards')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.premises')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.rates')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.tenants')),
            ],
        ),
    ]
