# Generated by Django 3.1.7 on 2021-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='deal_is_in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
