# Generated by Django 3.1.7 on 2021-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_deals_deal_is_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='tenant_name',
            field=models.CharField(default='ФИО или название компании', max_length=255),
        ),
    ]
