# Generated by Django 3.1.7 on 2021-03-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Premises_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_time', models.CharField(max_length=255)),
                ('fixed_or_non_fixed', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('premise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.premises_types')),
            ],
        ),
        migrations.CreateModel(
            name='Premises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square', models.PositiveIntegerField()),
                ('number_of_workplaces', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('premise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_side.premises_types')),
            ],
        ),
    ]
