# Generated by Django 3.1.7 on 2021-11-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
