# Generated by Django 3.1.7 on 2021-11-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0002_rent_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_form',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
